jQuery ($) ->
  sel_pref = $('#prefs')
  sel_area = $('#areas')

  updateList = ->
    sel_area.children().remove()

    switch $(this).children('option:selected').val()
      when '0'
        sel_area.append('<option value="0">宗谷地方</option>')
        sel_area.append('<option value="1">上川地方</option>')
        sel_area.append('<option value="2">留萌地方</option>')
        sel_area.append('<option value="3">網走地方</option>')
        sel_area.append('<option value="4">北見地方</option>')
        sel_area.append('<option value="5">紋別地方</option>')
        sel_area.append('<option value="6">根室地方</option>')
        sel_area.append('<option value="7">釧路地方</option>')
        sel_area.append('<option value="8">十勝地方</option>')
        sel_area.append('<option value="9">胆振地方</option>')
        sel_area.append('<option value="10">日高地方</option>')
        sel_area.append('<option value="11">石狩地方</option>')
        sel_area.append('<option value="12">空知地方</option>')
        sel_area.append('<option value="13">後志地方</option>')
        sel_area.append('<option value="14">渡島地方</option>')
        sel_area.append('<option value="15">檜山地方</option>')
      when '1'
        sel_area.append('<option value="0">津軽</option>')
        sel_area.append('<option value="1">下北</option>')
        sel_area.append('<option value="2">三八上北</option>')
      when '2'
        sel_area.append('<option value="0">沿岸</option>')
        sel_area.append('<option value="1">内陸</option>')
      when '3'
        sel_area.append('<option value="0">内陸</option>')
        sel_area.append('<option value="1">沿岸北部</option>')
        sel_area.append('<option value="2">沿岸南部</option>')
      when '4'
        sel_area.append('<option value="0">村山</option>')
        sel_area.append('<option value="1">置賜</option>')
        sel_area.append('<option value="2">庄内</option>')
        sel_area.append('<option value="3">最上</option>')
      when '5'
        sel_area.append('<option value="0">東部</option>')
        sel_area.append('<option value="1">西部</option>')
      when '6'
        sel_area.append('<option value="0">中通り</option>')
        sel_area.append('<option value="1">浜通り</option>')
        sel_area.append('<option value="2">会津</option>')
      when '7'
        sel_area.append('<option value="0">北部</option>')
        sel_area.append('<option value="1">南部</option>')
      when '8'
        sel_area.append('<option value="0">南部</option>')
        sel_area.append('<option value="1">北部</option>')
      when '9'
        sel_area.append('<option value="0">南部</option>')
        sel_area.append('<option value="1">北部</option>')
      when '10'
        sel_area.append('<option value="0">南部</option>')
        sel_area.append('<option value="1">北部</option>')
        sel_area.append('<option value="2">秩父地方</option>')
      when '11'
        sel_area.append('<option value="0">北西部</option>')
        sel_area.append('<option value="1">北東部</option>')
        sel_area.append('<option value="2">南部</option>')
      when '12'
        sel_area.append('<option value="0">東京地方</option>')
        sel_area.append('<option value="1">伊豆諸島北部</option>')
        sel_area.append('<option value="2">伊豆諸島南部</option>')
        sel_area.append('<option value="3">小笠原諸島</option>')
      when '13'
        sel_area.append('<option value="0">東部</option>')
        sel_area.append('<option value="1">西部</option>')
      when '14'
        sel_area.append('<option value="0">中･西部</option>')
        sel_area.append('<option value="1">東部･富士五湖</option>')
      when '15'
        sel_area.append('<option value="0">北部</option>')
        sel_area.append('<option value="1">中部</option>')
        sel_area.append('<option value="2">南部</option>')
      when '16'
        sel_area.append('<option value="0">下越</option>')
        sel_area.append('<option value="1">中越</option>')
        sel_area.append('<option value="2">上越</option>')
        sel_area.append('<option value="3">佐渡</option>')
      when '17'
        sel_area.append('<option value="0">東部</option>')
        sel_area.append('<option value="1">西部</option>')
      when '18'
        sel_area.append('<option value="0">加賀</option>')
        sel_area.append('<option value="1">能登</option>')
      when '19'
        sel_area.append('<option value="0">嶺北</option>')
        sel_area.append('<option value="1">嶺南</option>')
      when '20'
        sel_area.append('<option value="0">中部</option>')
        sel_area.append('<option value="1">伊豆</option>')
        sel_area.append('<option value="2">東部</option>')
        sel_area.append('<option value="3">西部</option>')
      when '21'
        sel_area.append('<option value="0">美濃地方</option>')
        sel_area.append('<option value="1">飛騨地方</option>')
      when '22'
        sel_area.append('<option value="0">西部</option>')
        sel_area.append('<option value="1">東部</option>')
      when '23'
        sel_area.append('<option value="0">北中部</option>')
        sel_area.append('<option value="1">南部</option>')
      when '24'
        sel_area.append('<option value="0">大阪府</option>')
      when '25'
        sel_area.append('<option value="0">南部</option>')
        sel_area.append('<option value="1">北部</option>')
      when '26'
        sel_area.append('<option value="0">南部</option>')
        sel_area.append('<option value="1">北部</option>')
      when '27'
        sel_area.append('<option value="0">南部</option>')
        sel_area.append('<option value="1">北部</option>')
      when '28'
        sel_area.append('<option value="0">北部</option>')
        sel_area.append('<option value="1">南部</option>')
      when '29'
        sel_area.append('<option value="0">北部</option>')
        sel_area.append('<option value="1">南部</option>')
      when '30'
        sel_area.append('<option value="0">東部</option>')
        sel_area.append('<option value="1">西部</option>')
        sel_area.append('<option value="2">隠岐</option>')
      when '31'
        sel_area.append('<option value="0">南部</option>')
        sel_area.append('<option value="1">北部</option>')
      when '32'
        sel_area.append('<option value="0">東部</option>')
        sel_area.append('<option value="1">中･西部</option>')
      when '33'
        sel_area.append('<option value="0">南部</option>')
        sel_area.append('<option value="1">北部</option>')
      when '34'
        sel_area.append('<option value="0">香川県</option>')
      when '35'
        sel_area.append('<option value="0">中予</option>')
        sel_area.append('<option value="1">東予</option>')
        sel_area.append('<option value="2">南予</option>')
      when '36'
        sel_area.append('<option value="0">北部</option>')
        sel_area.append('<option value="1">南部</option>')
      when '37'
        sel_area.append('<option value="0">中部</option>')
        sel_area.append('<option value="1">東部</option>')
        sel_area.append('<option value="2">西部</option>')
      when '38'
        sel_area.append('<option value="0">西部</option>')
        sel_area.append('<option value="1">中部</option>')
        sel_area.append('<option value="2">東部</option>')
        sel_area.append('<option value="3">北部</option>')
      when '39'
        sel_area.append('<option value="0">福岡地方</option>')
        sel_area.append('<option value="1">北九州地方</option>')
        sel_area.append('<option value="2">筑豊地方</option>')
        sel_area.append('<option value="3">筑後地方</option>')
      when '40'
        sel_area.append('<option value="0">南部</option>')
        sel_area.append('<option value="1">北部</option>')
      when '41'
        sel_area.append('<option value="0">南部</option>')
        sel_area.append('<option value="1">北部</option>')
        sel_area.append('<option value="2">壱岐･対馬</option>')
        sel_area.append('<option value="3">五島</option>')
      when '42'
        sel_area.append('<option value="0">熊本地方</option>')
        sel_area.append('<option value="1">阿蘇地方</option>')
        sel_area.append('<option value="2">天草･芦北地方</option>')
        sel_area.append('<option value="3">球磨地方</option>')
      when '43'
        sel_area.append('<option value="0">中部</option>')
        sel_area.append('<option value="1">北部</option>')
        sel_area.append('<option value="2">西部</option>')
        sel_area.append('<option value="3">南部</option>')
      when '44'
        sel_area.append('<option value="0">南部平野部</option>')
        sel_area.append('<option value="1">北部平野部</option>')
        sel_area.append('<option value="2">南部山沿い</option>')
        sel_area.append('<option value="3">北部山沿い</option>')
      when '45'
        sel_area.append('<option value="0">薩摩地方</option>')
        sel_area.append('<option value="1">大隅地方</option>')
        sel_area.append('<option value="2">種子島地方･屋久島地方</option>')
        sel_area.append('<option value="3">奄美地方</option>')
      when '46'
        sel_area.append('<option value="0">本島中南部</option>')
        sel_area.append('<option value="1">本島北部</option>')
        sel_area.append('<option value="2">久米島</option>')
        sel_area.append('<option value="3">大東島地方</option>')
        sel_area.append('<option value="4">宮古島地方</option>')
        sel_area.append('<option value="5">石垣島地方</option>')
        sel_area.append('<option value="6">与那国島地方</option>')

  sel_pref.on('change', updateList)

  updateList.call(sel_pref)
  if registered_area_id = sel_area.data('registered')
    sel_area.children('option').eq([registered_area_id]).attr('selected', 'selected')
